service: employee-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 512

functions:
  employeeFunc:
    handler: index.handler
    events:
      - http:
          path: employees
          method: get
      - http:
          path: employees/{employeeId}
          method: get
      - http:
          path: employees
          method: post
      - http:
          path: employees/{employeeId}
          method: put
      - http:
          path: employees/{employeeId}
          method: delete

plugins:
  - serverless-offline
